//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.15 at 10:54:12 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://batch.jsr352/jsl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jsr352.batch.jsl;
