//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.05 at 01:05:36 PM EDT 
//


package com.ibm.jbatch.jsl.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Chunk complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Chunk">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reader" type="{https://jakarta.ee/xml/ns/jakartaee}ItemReader"/>
 *         &lt;element name="processor" type="{https://jakarta.ee/xml/ns/jakartaee}ItemProcessor" minOccurs="0"/>
 *         &lt;element name="writer" type="{https://jakarta.ee/xml/ns/jakartaee}ItemWriter"/>
 *         &lt;element name="checkpoint-algorithm" type="{https://jakarta.ee/xml/ns/jakartaee}CheckpointAlgorithm" minOccurs="0"/>
 *         &lt;element name="skippable-exception-classes" type="{https://jakarta.ee/xml/ns/jakartaee}ExceptionClassFilter" minOccurs="0"/>
 *         &lt;element name="retryable-exception-classes" type="{https://jakarta.ee/xml/ns/jakartaee}ExceptionClassFilter" minOccurs="0"/>
 *         &lt;element name="no-rollback-exception-classes" type="{https://jakarta.ee/xml/ns/jakartaee}ExceptionClassFilter" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="checkpoint-policy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="item-count" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="time-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skip-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retry-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Chunk", propOrder = {
    "reader",
    "processor",
    "writer",
    "checkpointAlgorithm",
    "skippableExceptionClasses",
    "retryableExceptionClasses",
    "noRollbackExceptionClasses"
})
public class Chunk {

    @XmlElement(required = true)
    protected ItemReader reader;
    protected ItemProcessor processor;
    @XmlElement(required = true)
    protected ItemWriter writer;
    @XmlElement(name = "checkpoint-algorithm")
    protected CheckpointAlgorithm checkpointAlgorithm;
    @XmlElement(name = "skippable-exception-classes")
    protected ExceptionClassFilter skippableExceptionClasses;
    @XmlElement(name = "retryable-exception-classes")
    protected ExceptionClassFilter retryableExceptionClasses;
    @XmlElement(name = "no-rollback-exception-classes")
    protected ExceptionClassFilter noRollbackExceptionClasses;
    @XmlAttribute(name = "checkpoint-policy")
    protected String checkpointPolicy;
    @XmlAttribute(name = "item-count")
    protected String itemCount;
    @XmlAttribute(name = "time-limit")
    protected String timeLimit;
    @XmlAttribute(name = "skip-limit")
    protected String skipLimit;
    @XmlAttribute(name = "retry-limit")
    protected String retryLimit;

    /**
     * Gets the value of the reader property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReader }
     *     
     */
    public ItemReader getReader() {
        return reader;
    }

    /**
     * Sets the value of the reader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReader }
     *     
     */
    public void setReader(ItemReader value) {
        this.reader = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link ItemProcessor }
     *     
     */
    public ItemProcessor getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemProcessor }
     *     
     */
    public void setProcessor(ItemProcessor value) {
        this.processor = value;
    }

    /**
     * Gets the value of the writer property.
     * 
     * @return
     *     possible object is
     *     {@link ItemWriter }
     *     
     */
    public ItemWriter getWriter() {
        return writer;
    }

    /**
     * Sets the value of the writer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemWriter }
     *     
     */
    public void setWriter(ItemWriter value) {
        this.writer = value;
    }

    /**
     * Gets the value of the checkpointAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link CheckpointAlgorithm }
     *     
     */
    public CheckpointAlgorithm getCheckpointAlgorithm() {
        return checkpointAlgorithm;
    }

    /**
     * Sets the value of the checkpointAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckpointAlgorithm }
     *     
     */
    public void setCheckpointAlgorithm(CheckpointAlgorithm value) {
        this.checkpointAlgorithm = value;
    }

    /**
     * Gets the value of the skippableExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public ExceptionClassFilter getSkippableExceptionClasses() {
        return skippableExceptionClasses;
    }

    /**
     * Sets the value of the skippableExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public void setSkippableExceptionClasses(ExceptionClassFilter value) {
        this.skippableExceptionClasses = value;
    }

    /**
     * Gets the value of the retryableExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public ExceptionClassFilter getRetryableExceptionClasses() {
        return retryableExceptionClasses;
    }

    /**
     * Sets the value of the retryableExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public void setRetryableExceptionClasses(ExceptionClassFilter value) {
        this.retryableExceptionClasses = value;
    }

    /**
     * Gets the value of the noRollbackExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public ExceptionClassFilter getNoRollbackExceptionClasses() {
        return noRollbackExceptionClasses;
    }

    /**
     * Sets the value of the noRollbackExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionClassFilter }
     *     
     */
    public void setNoRollbackExceptionClasses(ExceptionClassFilter value) {
        this.noRollbackExceptionClasses = value;
    }

    /**
     * Gets the value of the checkpointPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckpointPolicy() {
        return checkpointPolicy;
    }

    /**
     * Sets the value of the checkpointPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckpointPolicy(String value) {
        this.checkpointPolicy = value;
    }

    /**
     * Gets the value of the itemCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCount(String value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the timeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeLimit() {
        return timeLimit;
    }

    /**
     * Sets the value of the timeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeLimit(String value) {
        this.timeLimit = value;
    }

    /**
     * Gets the value of the skipLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkipLimit() {
        return skipLimit;
    }

    /**
     * Sets the value of the skipLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkipLimit(String value) {
        this.skipLimit = value;
    }

    /**
     * Gets the value of the retryLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryLimit() {
        return retryLimit;
    }

    /**
     * Sets the value of the retryLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryLimit(String value) {
        this.retryLimit = value;
    }

/**
 * Copyright 2013 International Business Machines Corp.
 *
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership. Licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
    /*
     * Appended by build tooling.
     */  
	public String toString() {
	    StringBuffer buf = new StringBuffer(250);
	    String chkAlgStr = checkpointAlgorithm == null ? "null" : checkpointAlgorithm.getRef();
	    buf.append("Chunk: checkpointAlgorithm = " + chkAlgStr);
	    buf.append(", skippableExceptions = " + skippableExceptionClasses);
	    buf.append(", retryableExceptions = " + retryableExceptionClasses);
	    buf.append(", reader = " + reader);
	    buf.append(", processor = " + processor);
	    buf.append(", writer = " + writer);
	    buf.append(", checkpointPolicy = " + checkpointPolicy);
	    buf.append(", itemCount = " + itemCount);
	    buf.append(", timeLimit = " + timeLimit);
	    buf.append(", skipLimit = " + skipLimit);
	    buf.append(", retryLimit = " + retryLimit);
	    buf.append("\n");
	    return buf.toString();
    }
}